name: Build Package with pkg

on:
  push:
    branches:
      - main # Change to the default branch of your repository

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # Choose the Node.js version you want to use

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps # Replace with your package manager (e.g., yarn)

      - name: Install pkg
        run: npm install -g pkg

      - name: Build Package with pkg
        run: pkg package.json --output ./ersatztv-filler # Modify this command as needed

      - name: Upload Package
        uses: actions/upload-artifact@v2
        with:
          path: ./ersatztv-filler
