name: Build Package with pkg

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # Choose the Node.js version you want to use

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps # Replace with your package manager (e.g., yarn)

      - name: Install pkg
        run: npm install -g pkg

      - name: create working dir
        run: mkdir builds # Modify this command as needed

      - name: Build Package with pkg
        run: pkg package.json # Modify this command as needed
        working-directory: /home/runner/work/ErsatzTV-Filler/ErsatzTV-Filler/builds

      - name: create zips
        run: |
          mkdir ersatztv-windows
          cp ersatztv-filler-windows ersatztv-filler-windows-ver/ersatztv-filler-windows
          cp /home/runner/work/ErsatzTV-Filler/ErsatzTV-Filler/Changelog.md /home/runner/work/ErsatzTV-Filler/ErsatzTV-Filler/builds/ersatztv-filler-windows-ver
          cp /home/runner/work/ErsatzTV-Filler/ErsatzTV-Filler/README.md /home/runner/work/ErsatzTV-Filler/ErsatzTV-Filler/builds/ersatztv-filler-windows-ver
          zip -r windows.zip ersatztv-filler-windows-ver
        working-directory: /home/runner/work/ErsatzTV-Filler/ErsatzTV-Filler/builds

      - name: Upload Package
        uses: actions/upload-artifact@v2
        with:
          path: /home/runner/work/ErsatzTV-Filler/ErsatzTV-Filler/builds
