name: Build Package with pkg and zip

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # Choose the Node.js version you want to use

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps # Replace with your package manager (e.g., yarn)

      - name: Install pkg
        run: npm install -g pkg

      - name: create working dir
        run: mkdir builds # Modify this command as needed

      - name: Build Package with pkg
        run: pkg package.json # Modify this command as needed
        working-directory: /home/runner/work/ErsatzTV-Filler/ErsatzTV-Filler

      - name: Check if commit has a tag
        id: check_tag
        run: echo ::set-output name=has_tag::$(git describe --tags --exact-match 2>/dev/null || echo "false")

      - name: Determine version
        id: determine_version
        run: |
          if [[ "${{ steps.check_tag.outputs.has_tag }}" == "false" ]]; then
            VERSION="${{ github.sha }}"
          else
            VERSION="${{ github.ref }}"
          fi
          echo "Version is $VERSION"
        shell: bash

      - name: create zip
        run: |
          zip -j /home/runner/work/ErsatzTV-Filler/ErsatzTV-Filler/builds/ersatztv-filler-windows-${{ steps.determine_version.outputs.VERSION }}.zip /home/runner/work/ErsatzTV-Filler/ErsatzTV-Filler/ersatztv-filler-win.exe /home/runner/work/ErsatzTV-Filler/ErsatzTV-Filler/README.md /home/runner/work/ErsatzTV-Filler/ErsatzTV-Filler/Changelog.md 
          zip -j /home/runner/work/ErsatzTV-Filler/ErsatzTV-Filler/builds/ersatztv-filler-macos-${{ steps.determine_version.outputs.VERSION }}.zip /home/runner/work/ErsatzTV-Filler/ErsatzTV-Filler/ersatztv-filler-macos /home/runner/work/ErsatzTV-Filler/ErsatzTV-Filler/README.md /home/runner/work/ErsatzTV-Filler/ErsatzTV-Filler/Changelog.md
          zip -j /home/runner/work/ErsatzTV-Filler/ErsatzTV-Filler/builds/ersatztv-filler-linux-${{ steps.determine_version.outputs.VERSION }}.zip /home/runner/work/ErsatzTV-Filler/ErsatzTV-Filler/ersatztv-filler-linux /home/runner/work/ErsatzTV-Filler/ErsatzTV-Filler/README.md /home/runner/work/ErsatzTV-Filler/ErsatzTV-Filler/Changelog.md
        working-directory: /home/runner/work/ErsatzTV-Filler/ErsatzTV-Filler

      - name: Upload Package
        uses: actions/upload-artifact@v2
        with:
          path: /home/runner/work/ErsatzTV-Filler/ErsatzTV-Filler/builds
