name: Node.js npm run dev

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm ci --legacy-peer-deps

      - name: Run npm run dev with Timeout
        run: |
          # Run the "npm run dev" command in the background
          npm run dev &
          # Get the process ID (PID) of the background process
          dev_pid=$!
          # Wait for a specific timeout (e.g., 60 seconds)
          timeout=60
          sleep $timeout
          # Check if the process is still running
          if ps -p $dev_pid > /dev/null; then
            # Process is still running, terminate it
            echo "The 'npm run dev' command is running for too long. Terminating..."
            kill $dev_pid
            exit 1
          else
            # Process has completed, check the exit status
            if [ $? -eq 0 ]; then
              echo "The 'npm run dev' command ran successfully."
            else
              echo "The 'npm run dev' command encountered an error."
              exit 1
            fi
          fi

      - name: Run npm run build
        run: npm run build --if-present

